FROM mingkhoi/java_notebook:1.0
WORKDIR /app

ENV PATH="/root/miniconda3/bin:$PATH"

SHELL ["/bin/bash", "-c", "conda", "activate", "default"]

RUN jupyter lab --ip=0.0.0.0 --port=8081 --no-browser --allow-root
RUN jupyter notebook --ip=0.0.0.0 --port=8082 --no-browser --allow-root

ENTRYPOINT ["tail", "-f", "/dev/null"]
